#!/bin/sh
#
# An example hook script to verify what is about to be committed.
# Called by "git commit" with no arguments.  The hook should
# exit with non-zero status after issuing an appropriate message if
# it wants to stop the commit.
#
# To enable this hook, rename this file to "pre-commit".

fgrep -q --exclude-dir node_modules --exclude-dir .githooks --exclude-dir .git --exclude yarn-error.log -r 'JSON.parse' .
if [ $? != 1 ]; then
	echo "JSON.parse not allowed. Please use Bourne.parse instead."
	exit 1
fi
